# Generated by Django 3.0.4 on 2020-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflation', models.DecimalField(decimal_places=2, default='4.5', max_digits=4)),
                ('typeCrop', models.CharField(blank=True, max_length=100, verbose_name='Crop type: ')),
                ('Productivity', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=4)),
                ('revenues', models.DecimalField(decimal_places=2, default='0', max_digits=4)),
                ('areaCrop', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
