# Generated by Django 3.1.2 on 2020-10-14 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Project default', max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(blank=True, verbose_name='Fecha de Inicio: ')),
                ('fecha_final', models.DateTimeField(blank=True, null=True, verbose_name='Fecha finalización: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleados', models.PositiveSmallIntegerField()),
                ('plantilla', models.CharField(choices=[('0', 'Gerente'), ('1', 'Comercial'), ('2', 'Administrativo'), ('3', 'Soporte')], default='0', max_length=20, verbose_name='Departamento')),
                ('sueldo_empleado', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='GastoSubstrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('SubstratoPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('CantidadSubstrato', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitSubstrato', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='0', max_length=1, verbose_name='unidad de medida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoGas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('CantidadGas', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitGas', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='0', max_length=1, verbose_name='unidad de medida')),
                ('PrecioGas', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el: ')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoFertilizante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('CantidadFertilizante', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitFertilizante', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='0', max_length=1, verbose_name='unidad de medida')),
                ('FertilizantePrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('EnvioPrecio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoElectrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('CantidadPotElec', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitPotElec', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='0', max_length=1, verbose_name='unidad de medida')),
                ('PotElectricaPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el: ')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(max_length=200)),
                ('cantidadGasto', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7)),
                ('TipoGasto', models.CharField(choices=[('0', 'Consulta Agricola'), ('1', 'Formación'), ('2', 'Entrenamiento'), ('3', 'POL en necesidades administrativas'), ('4', 'Gastos de Oficina'), ('5', 'Gastos de Entretenimiento'), ('6', 'Gastos de Viajes'), ('7', 'Servicios de Información'), ('8', 'Gasto seguro de propiedad')], default='0', max_length=1)),
                ('fecha_gasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
