# Generated by Django 3.0.4 on 2020-11-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Area(m2): ')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Start date: ')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Finish date: ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='VariosGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariosGasto', models.CharField(choices=[('0', 'Cultivation equipment'), ('1', 'Overall'), ('2', 'Certifications'), ('3', 'Other expenses')], default='0', max_length=1, verbose_name='Miscellaneous expenses')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('VariosGastoDescripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description: ')),
                ('VariosGastoCantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Quantity: ')),
                ('unitVariosGasto', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('VariosGastoPrecio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Price')),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='taxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vatOutgoing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='VAT-outgoing: ')),
                ('vatIncluded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='VAT-included: ')),
                ('propertyTax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Property Tax: ')),
                ('landTax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Land Tax: ')),
                ('taxOnProfits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Tax on profits: ')),
                ('socSecContributions', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Social security contributions: ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleados', models.PositiveSmallIntegerField()),
                ('plantilla', models.CharField(choices=[('Manager', 'Manager'), ('Commercial', 'Commercial'), ('Administrative', 'Administrative'), ('Support', 'Support')], default='Manager', max_length=30, verbose_name='Departament')),
                ('sueldo_empleado', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='macroeconomicsIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Inflation per Country: ')),
                ('discountRate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Discount rate: ')),
                ('grownRateFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='The grown rate of the final cash flow: ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoSubstrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('SubstratoPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('CantidadSubstrato', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitSubstrato', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoSemillas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('TipoDeSemillas', models.TextField(blank=True, max_length=250, verbose_name='Seed type: ')),
                ('CantidadSemillas', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitSemillas', models.CharField(blank=True, choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('SemillasPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Seeds price: ')),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoRemedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('RemediosPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('CantidadRemedios', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitRemedios', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoLimpieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('CantidadBasuraSolida', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='solid garbage quantity: ')),
                ('unitBasuraSolida1', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=30, verbose_name='unit of measurement')),
                ('RetiradaBasuraSolidaPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='solid garbage price: ')),
                ('CantidadLimpiezaAguasResiduales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Wastewater quantity:')),
                ('unitLimpiezaAguasResiduales', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=30, verbose_name='unit of measurement')),
                ('GastosLimpiezaAguasResiduales', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Wastewater price: ')),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoGas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('CantidadGas', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitGas', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('PrecioGas', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at: ')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoFertilizante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('CantidadFertilizante', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitFertilizante', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('FertilizantePrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Description: ')),
                ('EnvioPrecio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Shipping price: ')),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoElectrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('CantidadPotElec', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitPotElec', models.CharField(choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=1, verbose_name='unit of measurement')),
                ('PotElectricaPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at: ')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('CombustiblePrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Fuel price: ')),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('CantidadCombustible', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Fuel Quantity: ')),
                ('unitCombustible', models.CharField(blank=True, choices=[('0', 'Kg/m2'), ('1', 'L/m2'), ('2', 'Units/m2')], default='0', max_length=30, verbose_name='unit of measurement')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
        migrations.CreateModel(
            name='GastoAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(max_length=200)),
                ('cantidadGasto', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7)),
                ('monedaBasuraSolida', models.CharField(choices=[('0', '€'), ('1', '€/kg'), ('2', 'x1000€/Mo.')], default='0', max_length=30, verbose_name='money parameter')),
                ('TipoGasto', models.CharField(choices=[('0', 'Agronomy consulting'), ('1', 'Education'), ('2', 'Training'), ('3', 'POL on administrative needs'), ('4', 'Office expenses'), ('5', 'Households costs. needs'), ('6', 'Entertainment expenses'), ('7', 'Travel expenses'), ('8', 'Information Services'), ('9', 'Property insurance')], default='0', max_length=1)),
                ('fecha_gasto', models.DateField(blank=True, null=True, verbose_name='Expense generated on:')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.Proyecto', verbose_name='Project: ')),
            ],
        ),
    ]
