# Generated by Django 3.0.4 on 2020-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoremedio',
            name='CantidadRemedios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Remedies quantity'),
        ),
        migrations.AlterField(
            model_name='gastoremedio',
            name='RemediosPrecio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Remedies price: '),
        ),
        migrations.AlterField(
            model_name='gastosemillas',
            name='CantidadSemillas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Seeds quantity'),
        ),
    ]
