# Generated by Django 3.0.4 on 2020-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0002_auto_20201117_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoelectrico',
            name='CantidadPotElec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Electric quantity: '),
        ),
        migrations.AlterField(
            model_name='gastoelectrico',
            name='PotElectricaPrecio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Electric price: '),
        ),
        migrations.AlterField(
            model_name='gastofertilizante',
            name='CantidadFertilizante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Fertilizer quantity: '),
        ),
        migrations.AlterField(
            model_name='gastofertilizante',
            name='FertilizantePrecio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=' Fertilizer Price: '),
        ),
        migrations.AlterField(
            model_name='gastosubstrato',
            name='CantidadSubstrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Substrate quantity: '),
        ),
        migrations.AlterField(
            model_name='gastosubstrato',
            name='SubstratoPrecio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Substrate price:'),
        ),
    ]
