# Generated by Django 3.1.2 on 2020-10-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0002_gastoremedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoSemillas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SemillasPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('TipoDeSemillas', models.CharField(blank=True, max_length=50)),
                ('CantidadSemillas', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitSemillas', models.CharField(blank=True, choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='0', max_length=1, verbose_name='unidad de medida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
