# Generated by Django 3.1.2 on 2020-10-15 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0005_auto_20201014_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariosGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariosGasto', models.CharField(choices=[('0', 'Equipo de cultivo'), ('1', 'Ropa de trabajo'), ('2', 'Certificaciones'), ('3', 'Otros gastos')], default='0', max_length=1, verbose_name='gastos varios')),
                ('fechaGasto', models.DateTimeField(blank=True, null=True, verbose_name='Gasto generado el:')),
                ('VariosGastoDescripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('VariosGastoCantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unitVariosGasto', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='0', max_length=1, verbose_name='unidad de medida')),
                ('VariosGastoPrecio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputapp.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
