# Generated by Django 3.0.6 on 2020-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CapitalStock', models.FloatField(default='0')),
                ('monedaStock', models.CharField(default='€', max_length=3)),
                ('CapitalDeudores', models.FloatField(default='0')),
                ('monedaDeudores', models.CharField(default='€', max_length=3)),
                ('CapitalAcreedores', models.FloatField(default='0')),
                ('monedaAcreedores', models.CharField(default='€', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GastosAdministrativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(blank=True, max_length=200)),
                ('FechaGasto', models.DateField()),
                ('Cantidad', models.FloatField(default='0')),
                ('TipoGasto', models.CharField(choices=[('Consulta Agricola', 'Agronomy_consulting'), ('Formación', 'Formacion'), ('Entrenamiento', 'Entrenamiento'), ('Necesidades administrativas', 'POL on administrative needs'), ('Gastos de Oficina', 'Office_expenses'), ('Gastos de Entretenimiento', 'Entertainment_expenses'), ('Gastos de Viajes', 'Travel_expenses'), ('Servicios de Información', 'Information_services'), ('Gasto seguro de propiedad', 'Property_Insurance')], default='Consulta Agricola', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GastosCultivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaActualizacion', models.DateField()),
                ('PotElectricaPrecio', models.FloatField(default='0')),
                ('CantidadPotElec', models.FloatField(default='0')),
                ('unitPotElec', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('PrecioGas', models.FloatField(default='0')),
                ('CantidadGas', models.FloatField(default='0')),
                ('unitGas', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('FertilizantePrecio', models.FloatField(default='0')),
                ('CantidadFertilizante', models.FloatField(default='0')),
                ('unitFertilizante', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('SubstratoPrecio', models.FloatField(default='0')),
                ('CantidadSubstrato', models.FloatField(default='0')),
                ('unitSubstrato', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('Empaquetamiento_TransportePrecio', models.FloatField(default='0')),
                ('RemediosPrecio', models.FloatField(default='0')),
                ('CantidadRemedios', models.FloatField(default='0')),
                ('unitRemedios', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('SemillasPrecio', models.FloatField(default='0')),
                ('CantidadSemillas', models.FloatField(default='0')),
                ('unitSemillas', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('CombustiblePrecio', models.FloatField(default='0')),
                ('CantidadCombustible', models.FloatField(default='0')),
                ('unitCombustible', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
                ('EquipoCultivoPrecio', models.FloatField(default='0')),
                ('RetiradaBasuraSolidaPrecio', models.FloatField(default='0')),
                ('OtrosGastos', models.FloatField(default='0')),
                ('RopaDeTrabajoGastos', models.FloatField(default='0')),
                ('CertificacionGastos', models.FloatField(default='0')),
                ('GastosLimpiezaAguasResiduales', models.FloatField(default='0')),
                ('CantidadLimpiezaAguasResiduales', models.FloatField(default='0')),
                ('unitLimpiezaAguasResiduales', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Unidades', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FondoFijo', models.BooleanField(default='true')),
                ('Num_empleados', models.PositiveIntegerField(default='0')),
                ('Plantilla', models.CharField(choices=[('Gerente', 'Gerente'), ('Comercial', 'Comercial'), ('Administrativo', 'Administrativo'), ('Soporte', 'Soporte')], default='S', max_length=20)),
                ('Sueldo', models.FloatField(default='0')),
            ],
        ),
        migrations.DeleteModel(
            name='GastosCultivo',
        ),
        migrations.DeleteModel(
            name='GastosGenerales',
        ),
    ]
