# Generated by Django 3.0.6 on 2020-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_app', '0002_auto_20201006_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='monedaAcreedores',
            field=models.CharField(default='€', max_length=1),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='monedaDeudores',
            field=models.CharField(default='€', max_length=1),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='monedaStock',
            field=models.CharField(default='€', max_length=1),
        ),
    ]
