# Generated by Django 3.0.6 on 2020-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_app', '0004_auto_20201006_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='CapitalAcreedores',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='CapitalDeudores',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='CapitalStock',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='monedaAcreedores',
            field=models.CharField(default='€', max_length=1),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='monedaDeudores',
            field=models.CharField(default='€', max_length=1),
        ),
        migrations.AlterField(
            model_name='capitaltrabajo',
            name='monedaStock',
            field=models.CharField(default='€', max_length=1),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadCombustible',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadFertilizante',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadGas',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadLimpiezaAguasResiduales',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadPotElec',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadRemedios',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadSemillas',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CantidadSubstrato',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CertificacionGastos',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='CombustiblePrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='Empaquetamiento_TransportePrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='EquipoCultivoPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='FertilizantePrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='GastosLimpiezaAguasResiduales',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='OtrosGastos',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='PotElectricaPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='PrecioGas',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='RemediosPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='RetiradaBasuraSolidaPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='RopaDeTrabajoGastos',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='SemillasPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='SubstratoPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
