# Generated by Django 3.1.2 on 2020-10-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_app', '0005_auto_20201006_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_proyecto', models.CharField(max_length=50)),
                ('Fecha_de_inicio', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CapitalTrabajo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Plantilla',
        ),
        migrations.AddField(
            model_name='personal',
            name='Plantillas',
            field=models.CharField(choices=[('0', 'Gerente'), ('1', 'Comercial'), ('2', 'Administrativo'), ('3', 'Soporte')], default='0', max_length=30, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='TipoGasto',
            field=models.CharField(choices=[('0', 'Consulta Agricola'), ('1', 'Formación'), ('2', 'Entrenamiento'), ('3', 'POL en necesidades administrativas'), ('4', 'Gastos de Oficina'), ('5', 'Gastos de Entretenimiento'), ('6', 'Gastos de Viajes'), ('7', 'Servicios de Información'), ('8', 'Gasto seguro de propiedad')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitCombustible',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitFertilizante',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitGas',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitLimpiezaAguasResiduales',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitPotElec',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitRemedios',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitSemillas',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='gastoscultivos',
            name='unitSubstrato',
            field=models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], default='Kilogramos', max_length=30, verbose_name='unidad de medida'),
        ),
    ]
